title: "안녕하세요, 박도연입니다."
author: "박도연"
description: "판교에서 웹사이트를 만들고있습니다."
more: "read more »"
url: "https://parkdoyeon.github.io/"
baseurl: ""
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - posts.html
  - dev-memo.html
  - about.md
#  - projects.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/twitter/"
  - github: "https://github.com/parkdoyeon"
  - envelope: "mailto:park.doyeonn@gmail.com"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
future: true